-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE INDEX "collection_ProgramPerson_name_gin" ON collection."ProgramPerson"
-- USING GIN ((name) gin_trgm_ops, (affiliation) gin_trgm_ops);
