version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: "no"
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      # TODO: set up Postgres security
      POSTGRES_PASSWORD: postgrespassword
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_DOCKER_IMAGE:-6.5}
    depends_on:
      - "postgres"
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: "no"
volumes:
  db_data:
