-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE INDEX "schedule_Event_name_gin" ON "schedule"."Event"
-- USING GIN (("name") gin_trgm_ops);
