-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "video"."VonageParticipantStream" add column "subconferenceId" uuid
--  null;
