-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "job_queues"."ImportJob" add column "outputs" jsonb
--  not null default '{}';
