-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE content."ElementType"
-- SET name = 'EXTERNAL_EVENT_LINK'
-- WHERE name = 'ZOOM';
