-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "job_queues"."ImportJob" add column "progressMaximum" integer
--  not null default '0';
