-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW "content"."ElementByAccessToken" AS
--  SELECT "Element".id,
--     "Element"."typeName",
--     "Element".name,
--     "Element".data,
--     "Element"."layoutData",
--     "Element"."accessToken",
--     "Item".title AS "itemTitle"
--    FROM content."Element"
--      JOIN content."Item" ON ("Item".id = "Element"."itemId");
