-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "registrant"."Registrant" add column "conferenceRole" text
--  not null default 'ATTENDEE';
