-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW content."ItemProgramPersonByAccessToken" AS
-- SELECT * FROM content."ItemProgramPerson";
