-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "collection"."Exhibition" add column "visibilityLevel" text
--  not null default 'INTERNAL';
