-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION registrant."isProgramPerson"(registrant_row registrant."Registrant")
--  RETURNS boolean
--  LANGUAGE sql
--  STABLE
-- AS $function$
--     SELECT EXISTS (
--         SELECT 1 FROM "collection"."ProgramPerson" AS person
--         WHERE person."registrantId" = registrant_row."id"
--     )
-- $function$;
