-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "collection"."ProgramPerson" add column "accessToken" text
--  not null default gen_random_uuid();
