INSERT INTO "ContentType" (name, description) VALUES
  ('ABSTRACT', 'Abstract Markdown text.'),
  ('TEXT', 'General-purpose Markdown text.'),
  ('VIDEO_FILE', 'File for a video (stored by Clowdr).'),
  ('VIDEO_URL', 'URL for a video (video is embedded in Clowdr UI).'),
  ('VIDEO_LINK', 'Link to a video (video is not embedded in Clowdr UI).'),
  ('POSTER_FILE', 'File for a poster image (stored by Clowdr).'),
  ('POSTER_URL', 'URL to a poster image (embedded in Clowdr UI).'),
  ('IMAGE_FILE', 'File for an image (stored by Clowdr).'),
  ('IMAGE_URL', 'URL to an image (embedded in Clowdr UI).'),
  ('PAPER_FILE', 'File for a paper (stored by Clowdr).'),
  ('PAPER_URL', 'URL to a paper (preview may be embedded in Clowdr UI e.g. PDF JS viewer).'),
  ('PAPER_LINK', 'Link for a paper (preview is not embedded in Clowdr UI).'),
  ('LINK', 'A generic URL.'),
  ('LINK_BUTTON', 'A URL for a link button.');
