-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW content."ElementByPersonAccessToken" AS
-- SELECT * FROM content."Element";
