-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "conference"."Conference" add column "lowestRoleWithAccess" text
--  null;
