-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "job_queues"."ChannelStackCreateJob" add constraint "ChannelStackCreateJob_stackLogicalResourceId_key" unique ("stackLogicalResourceId");
