web: node --enable-source-maps ./build/web-server.js

chatMessagesDistributionWorker: node --enable-source-maps ./build/workers/chat/messages/distribution.js
chatMessagesWritebackWorker: node --enable-source-maps ./build/workers/chat/messages/writeback.js

chatReactionsDistributionWorker: node --enable-source-maps ./build/workers/chat/reactions/distribution.js
chatReactionsWritebackWorker: node --enable-source-maps ./build/workers/chat/reactions/writeback.js

analyticsConferenceComputationWorker: node --enable-source-maps ./build/workers/analytics/conferenceComputation.js
analyticsItemComputationWorker: node --enable-source-maps ./build/workers/analytics/itemComputation.js
analyticsElementComputationWorker: node --enable-source-maps ./build/workers/analytics/elementComputation.js
analyticsRoomComputationWorker: node --enable-source-maps ./build/workers/analytics/roomComputation.js
