web: node ./build/web-server.js

chatMessagesDistributionWorker: node ./build/workers/chat/messages/distribution.js
chatMessagesWritebackWorker: node ./build/workers/chat/messages/writeback.js

chatReactionsDistributionWorker: node ./build/workers/chat/reactions/distribution.js
chatReactionsWritebackWorker: node ./build/workers/chat/reactions/writeback.js
