-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "content"."Element" add column "accessToken" text
--  not null default gen_random_uuid();
