-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "schedule"."Event" add column "automaticParticipationSurvey" boolean
--  not null default 'false';
